python3.8 generate_train.py --form CONST --indir ./treebanks/constituent/penn-treebank       --outlbl ./labels/constituent/penn-treebank         --outcfg ./ncrf_configs/penn-treebank      --outmodel ./models/penn-treebank        --outdec ./labels_dec/constituent/penn-treebank         --t_config ./default_train.config --d_config ./default_decode.config

python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Spanish-GSD     --outlbl ./labels/dependencies/UD_Spanish-GSD       --outcfg ./ncrf_configs/UD_Spanish-GSD      --outmodel ./models/UD_Spanish-GSD      --outdec ./labels_dec/dependencies/UD_Spanish-GSD       --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Arabic-PADT     --outlbl ./labels/dependencies/UD_Arabic-PADT       --outcfg ./ncrf_configs/UD_Arabic-PADT      --outmodel ./models/UD_Arabic-PADT      --outdec ./labels_dec/dependencies/UD_Arabic-PADT       --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Chinese-GSD     --outlbl ./labels/dependencies/UD_Chinese-GSD       --outcfg ./ncrf_configs/UD_Chinese-GSD      --outmodel ./models/UD_Chinese-GSD      --outdec ./labels_dec/dependencies/UD_Chinese-GSD       --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_English-EWT     --outlbl ./labels/dependencies/UD_English-EWT       --outcfg ./ncrf_configs/UD_English-EWT      --outmodel ./models/UD_English-EWT      --outdec ./labels_dec/dependencies/UD_English-EWT       --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Estonian-EWT    --outlbl ./labels/dependencies/UD_Estonian-EWT      --outcfg ./ncrf_configs/UD_Estonian-EWT     --outmodel ./models/UD_Estonian-EWT     --outdec ./labels_dec/dependencies/UD_Estonian-EWT      --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Finnish-FTB     --outlbl ./labels/dependencies/UD_Finnish-FTB       --outcfg ./ncrf_configs/UD_Finnish-FTB      --outmodel ./models/UD_Finnish-FTB      --outdec ./labels_dec/dependencies/UD_Finnish-FTB       --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_French-GSD      --outlbl ./labels/dependencies/UD_French-GSD        --outcfg ./ncrf_configs/UD_French-GSD       --outmodel ./models/UD_French-GSD       --outdec ./labels_dec/dependencies/UD_French-GSD        --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Galician-CTG    --outlbl ./labels/dependencies/UD_Galician-CTG      --outcfg ./ncrf_configs/UD_Galician-CTG     --outmodel ./models/UD_Galician-CTG     --outdec ./labels_dec/dependencies/UD_Galician-CTG      --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Greek-GDT       --outlbl ./labels/dependencies/UD_Greek-GDT         --outcfg ./ncrf_configs/UD_Greek-GDT        --outmodel ./models/UD_Greek-GDT        --outdec ./labels_dec/dependencies/UD_Greek-GDT         --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Italian-ISDT    --outlbl ./labels/dependencies/UD_Italian-ISDT      --outcfg ./ncrf_configs/UD_Italian-ISDT     --outmodel ./models/UD_Italian-ISDT     --outdec ./labels_dec/dependencies/UD_Italian-ISDT      --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Korean-GSD      --outlbl ./labels/dependencies/UD_Korean-GSD        --outcfg ./ncrf_configs/UD_Korean-GSD       --outmodel ./models/UD_Korean-GSD       --outdec ./labels_dec/dependencies/UD_Korean-GSD        --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Polish-LFG      --outlbl ./labels/dependencies/UD_Polish-LFG        --outcfg ./ncrf_configs/UD_Polish-LFG       --outmodel ./models/UD_Polish-LFG       --outdec ./labels_dec/dependencies/UD_Polish-LFG        --t_config ./default_train.config --d_config ./default_decode.config
python3.8 generate_train.py --form DEPS --indir ./treebanks/dependencies/UD_Portuguese-GSD  --outlbl ./labels/dependencies/UD_Portuguese-GSD    --outcfg ./ncrf_configs/UD_Portuguese-GSD   --outmodel ./models/UD_Portuguese-GSD   --outdec ./labels_dec/dependencies/UD_Portuguese-GSD    --t_config ./default_train.config --d_config ./default_decode.config

